name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: master

env:
  IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login using Github Token
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_REPO }}

      - name: Build and push to GitHub Packages
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_REPO }}:buildcache,mode=max
          push: true

      - name: Prepare image list
        id: images
        run: |
          NEWIMAGE=${{ env.IMAGE_REPO }}@${{ steps.build.outputs.digest }}
          IMAGES="[{\"environment\":\"prod\",\"target\": \"dashboard\",\"newImage\":\"$NEWIMAGE\"}]"
          echo "::set-output name=images::$(echo $IMAGES | base64 -w 0)"

      - name: Update images
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Images
          repo: wireless-monkeys/infrastructure
          token: ${{ secrets.DISPATCH_PAT }}
          inputs: '{ "images": "${{ steps.images.outputs.images }}", "name": "Wireless Monkeys", "email": "112172550+wireless-monkeys-sa@users.noreply.github.com" }'
